### ISSUE TITLE
Smart fan screen

### ISSUE THREAD

**Issue by HetviSoni** [Lakhankumawat/smart-home-app#15]
'smart_ac' screen is opening on clicking 'Smart fan' screen as Smart fan screen is not yet made.
I would like to work on creating the 'smart_fan' screen. Please assign me this issue under the GSSoC label.

**Comment by Lakhankumawat** [comment]
This issue is assigned as Level-3 because you'll be controlling the actual speed of the animation from the slider below , if the fan is off as shown in UI button it should not rotate and if we on it and increase it's speed or decrease it's speed then in must change it's fan rotation speed accordingly .

**Comment by Lakhankumawat** [comment]
This is the lottie animation used on the page : https://assets5.lottiefiles.com/packages/lf20_FFesjD.json

Make sure you are able to add these complex custom animations with animationtickerprovidermixin in flutter .
